### ISSUE TITLE
[Enhancement]: cncf graduation checklist

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#3298]
### Is there an existing issue for this?

- [x] I have searched all the existing issues

### What would you like to be added?

Project Repo(s): [https://github.com/cubefs/cubefs](https://github.com/cubefs/cubefs)
Project Site:  [https://cubefs.io](https://cubefs.io/)
Communication: [cubefs.slack.com](https://cubefs.slack.com/)

Project points of contacts: leon chang, changliang@oppo.com

### Adoption Assertion

_The project has been adopted by the following organizations in a testing and integration or production capacity:_
ADOPTERS: [link to md#section](https://github.com/cubefs/cubefs/edit/master/ADOPTERS.md)

### Required

- [x] **Give a presentation and engage with the domain specific TAG(s) to increase awareness**

 

Record of CubeFS presentation at the Storage TAG on April 24, 2024. [link to video](https://www.youtube.com/watch?v=UgRBZhzfr4w)

- [x]  **All project metadata and resources are [vendor-neutral].**

 

- In CubeFS governance.md, we require vendur-neutrality: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#vendor-neutrality)
- Maintainers of CubeFS coming from JD, OPPO, BEIKE etc.: [link to md#section](https://github.com/cubefs/cubefs/blob/master/MAINTAINERS.md#maintainers)
- Steering committee member: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#expectations-from-the-steering-committee)

- [ ] **Review and acknowledgement of expectations for graduated projects and requirements for moving forward through the CNCF Maturity levels.**		
   - [ ] Met during Project's application on DD-MMM-YYYY.

 

Completion of this due diligence document, resolution of concerns raised, and presented for public comment satisifies the Due Diligence Review criteria.

- [x] **Additional documentation as appropriate for project type, e.g.: installation documentation, end user documentation, reference implementation and/or code samples.**

 

CubeFS introduction documentation: [link](https://cubefs.io/docs/master/overview/introduction.html)
CubeFS installation documentation: [link](https://github.com/cubefs/cubefs/blob/master/INSTALL.md)
CubeFS end user documentation: [link](https://cubefs.io/docs/master/user-guide/volume.html)

## Governance and Maintainers

Note: this section may be augmented by the completion of a Governance Review from TAG Contributor Strategy.

### Suggested

- [x]  **Governance has continuously been iterated upon by the project as a result of their experience applying it, with the governance history demonstrating evolution of maturity alongside the project's maturity evolution.**

 
In the past period, the core maintainer of CubeFS has been continuously optimizing around governance, hoping that the community will be clear, reasonable, efficient, and explicit in governance to help the community develop.Below are some governance document changes and pull requests made in response to governance documents, all of which have been voted on and presented by maintainers.

- Update the Governance Document by most of maintainers: [link to pr](https://github.com/cubefs/cubefs/pull/3312)
- Update the Governance Document to eliminate the role of the leader:[link to pr](https://github.com/cubefs/cubefs/pull/3382)
- Update maintainer list according to activity and add steering commitee member: [link to pr](https://github.com/cubefs/cubefs/pull/3311)

### Required

- [x] **Clear and discoverable project governance documentation.**

 
CubeFS initially referenced governance documents from other projects and made appropriate adjustments to the documents in recent months. You can refer to the document revision history for details.

CubeFS governance documentation: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md)

- [x] **Governance is up to date with actual project activities, including any meetings, elections, leadership, or approval processes.**

 

- CubeFS Meeting-Schedule: [link](https://github.com/cubefs/cubefs-community/wiki/Meeting-Schedule)
- 2024-Recruiting developers: [link to issue](https://github.com/cubefs/cubefs/issues/3105)
- The establishment of the Steering Committee and clarification of its members in CubeFS: [link to issue](https://github.com/cubefs/cubefs/pull/3311#issue-2238919813)
- Update the document of the roadmap to improve readability and include features that are in preparation but not yet scheduled: [link to pr](https://github.com/cubefs/cubefs/pull/3358)
- Adding governance rules related to SIGs.: [link to pr](https://github.com/cubefs/cubefs/pull/3430)
- Adding governance rules related to RoadMap.: [link to pr](https://github.com/cubefs/cubefs/pull/3430)

- [x] **Governance clearly documents  [vendor-neutral](https://contribute.cncf.io/maintainers/community/vendor-neutrality/) of project direction.**

 

The governance document [link](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#vendor-neutrality) clearly defines matters related to information transparency, channel transparency, decision-making, and other aspects among vendors.

- Roadmap Governance
	- Changes in project Roadmap rules:[link](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-project-roadmap)
	- [Roadmap Update Example](https://github.com/cubefs/cubefs/pull/3358)
- Management and maintainance of shared communication channels with vendors, such as social media and messaging platforms, with the rule of taking turns for being on duty.In China, we operate three WeChat groups, and we have also created a cubefs channel on Slack at https://cubefs.slack.com, which includes a development channel. Additionally, we have a Slack channel on CNCF at [link](https://cloud-native.slack.com/archives/C014X3T1DDJ). All of these channels include our maintainer members from various vendors.The Entrance is open:[link](https://github.com/cubefs/cubefs#community)
- Public events of the project are open to all vendors for participation and topic involvement.	We emphasize the importance of transparent information sharing, such as external conference details and maintainer personnel list updates. We will collect feedback through the email address cncf-cubefs-maintainers@lists.cncf.io.
- Community meetings, activities, and resources will be selected for participation by the leadership team. Maintainers can apply and be selected to participate.
- Architectural decisions require community consensus and agreement by the majority of maintainers, reached during community meetings.For example:
	- Governance update [link](https://github.com/cubefs/cubefs/pull/3430)
	- Update maintainer list [link](https://github.com/cubefs/cubefs/pull/3311)

- [x] **Document how the project makes decisions on leadership roles, contribution acceptance, requests to the CNCF, and changes to governance or project goals.**

 

- Decision making process on leadership roles: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#decision-making-process)
- Contribution acceptance: [link to md#section](https://github.com/cubefs/cubefs/blob/master/CONTRIBUTING.md)
- Requests to the CNCF
	- CubeFS and cncf: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#cubefs-and-cncf)
	- Liaison officer for cncf: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#cubefs-and-cncf)
- Changes to governance or project goals
	- Changes to governance or project goals: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-project-governance)
	- Steering Committee Member is responsible for formulation  roadmap: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#expectations-from-the-steering-committee)

- [x] **Document how role, function-based members, or sub-teams are assigned, onboarded, and removed for specific teams (example: Security Response Committee).**

 

In the main CubeFS project, roles include steering committee members, maintainers, and contributors. The conditions and methods for role changes can be found in our governance documents. Apart from the main project, we have two SIG groups, with detailed governance explanations in their autonomous documents. Lastly, we also have a [security committee](https://github.com/cubefs/cubefs/blob/master/security/security-release-process.md#product-security-committee), with role descriptions outlined in the documentation
- Main CubeFS project role update according to governance documentation:
	- [Becoming a Maintainer](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#becoming-a-maintainer)
	- [Changes in Maintainership](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-maintainership)
	- [https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#expectations-from-the-steering-committee)
	- [Changes in Steering Committee](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-steering-committee)
	- [Becoming a committer](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#becoming-a-committer)
	- [Becoming a committer](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-commitership)
- Governance of to SIGs. Rules for assignment, onboarding, and removal: [link to pr](https://github.com/cubefs/cubefs/pull/3430)
- Product Security Committee Membership: Rules for assignment, onboarding, and removal.[link to md#section](https://github.com/cubefs/cubefs/blob/master/security/security-release-process.md#product-security-committee-membership)

- [x] **Document complete list of current maintainers, including names, contact information, domain of responsibility, and affiliation.**

 
Details information about current maintainers: [link to md#section](https://github.com/cubefs/cubefs/blob/master/MAINTAINERS.md)

- [X] **A number of active maintainers which is appropriate to the size and scope of the project.**

 
CubeFS is a complex project with relevant maintainers and committers for each module, driving the evolution of modules from architecture to implementation, and maintaining the iterative development of modules on a daily basis.
The maintainers are assigned to their respective modules, and the majority of maintainers have made a significant number of contributions in the past year.
Details information about current maintainers: [link to md#section](https://github.com/cubefs/cubefs/blob/master/MAINTAINERS.md)

- [X] **Document a complete maintainer lifecycle process (including roles, onboarding, offboarding, and emeritus status).**

 
- How to become a maintainer: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#becoming-a-maintainer)
- Document changes in maintainership,onboarding, offboarding: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-maintainership)

- [x] **Demonstrate usage of the maintainer lifecycle with outcomes, either through the addition or replacement of maintainers as project events have required.**

 
Currently, the maintainers of CubeFS are generally balanced between major vendors and active contributors. 
Some personnel changes have been made based on activity levels, and new key contributors need to be added to the maintainer list.
- The latest personnel changes are based on the new governance document and voting principles.[link to pr](https://github.com/cubefs/cubefs/pull/3311)
- Historical changes: New maintainers are being added because individuals have been the main contributors to the project.[link to pr](https://github.com/cubefs/cubefs/pull/2228/files)
- Historical changes: The maintainer update is due to insufficient activity levels from many individuals.[link to pr](https://github.com/cubefs/cubefs/pull/3044)
- Rules: How to become a maintainer.[link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-maintainership)

- [X] **Project maintainers from at least 2 organizations that demonstrates survivability.**

Maintainers from JD, OPPO, BIGO, SHOPPE,SBEIKE, etc.[link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#changes-in-maintainership)

 

- [X] **Code and Doc ownership in Github and elsewhere matches documented governance roles.**
 
The CubeFS community can continue to evolve iteratively, with several key vendors continuously investing in community development. Their contributions may take different forms; for example, OPPO maintains the advancement of the core, while JINGDONG, BIGO, and BEIKE consistently provide very important features.

- The top 6 contributors with the highest number of contributions are all maintainers.[link](https://github.com/cubefs/cubefs/graphs/contributors)
- The significant [branch](https://github.com/cubefs/cubefs/tree/release_low_latency_jd) from JD.com provides a multitude of important features. It will eventually merge with the main branch, and we are working on this.
- Maintainers have expertise in the domain fields of the project and are listed in the maintainer documentation.[link to md#section](https://github.com/cubefs/cubefs/blob/master/MAINTAINERS.md#maintainers)

- [X] **Document agreement that project will adopt CNCF Code of Conduct.**

 
Code of conduct of CubeFS: [link to md#section](https://github.com/cubefs/cubefs/blob/master/CODE_OF_CONDUCT.md)

- [X] **CNCF Code of Conduct is cross-linked from other governance documents.**

CubeFS Governance documents are interconnected with the CNCF Code of Conduct.[link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#code-of-conduct)

- [X] **All subprojects, if any, are listed.**

 

The sub-projects of CubeFS are closely related to the main project, serving as essential supplements that need to be released synchronously with the main version when necessary. Among other listed projects, some are for exploratory purposes while others are related to peripheral ecosystem products.

[Sub-Project governace rules](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#sub-projects)

The following projects are associated with CubeFS and serve as components. 
- Adapt CubeFS installation to helm in the Kubernetes ecosystem: [cubefs-helm](https://github.com/cubefs/cubefs-helm)
- Adapt CubeFS management to CSI (Container Storage Interface): [cubefs-csi](https://github.com/cubefs/cubefs-csi)
- Dashboard for CubeFS:[cubefs-dashboard](https://github.com/cubefs/cubefs-dashboard)

- [x] **If the project has subprojects: subproject leadership, contribution, maturity status documented, including add/remove process.**

 
All subprojects have their own repositories but follow the same governance mechanism as the main project. [link](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md)
[cubefs-helm Governance](https://github.com/cubefs/cubefs-csi#governance)
[cubefs-csi Governance](https://github.com/cubefs/cubefs-csi#governance)
[cubefs-dashboard Governance](https://github.com/cubefs/cubefs-dashboard#governance)
## Contributors and Community

Note: this section may be augmented by the completion of a Governance Review from TAG Contributor Strategy.

### Suggested

- [x] **Contributor ladder with multiple roles for contributors.**
Cubefs have multiple roles for contributors
- Commiter: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#committer)
- Maintainer: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#expectations-from-maintainers)
- Steering committee member: [link to md#section](https://github.com/cubefs/cubefs/blob/master/GOVERNANCE.md#expectations-from-the-steering-committee)

 

### Required

- [x] **Clearly defined and discoverable process to submit issues or changes.**

 
CubeFS process to submit issues or changes: [link to md#section](https://github.com/cubefs/cubefs/blob/master/CONTRIBUTING.md)

- [x] **Project must have, and document, at least one public communications channel for users and/or contributors.**

 
CubeFS communications channel: [link](https://github.com/cubefs/cubefs#community)

- [x] **List and document all project communication channels, including subprojects (mail list/slack/etc.).  List any non-public communications channels and what their special purpose is.**

 
The communication channels for all CubeFS projects are shared: [link](https://github.com/cubefs/cubefs#community)

- [X] **Up-to-date public meeting schedulers and/or integration with CNCF calendar.**

 
CubeFS meeting schedulers already added to CNCF calendar: [link](https://github.com/cubefs/cubefs-community/wiki/Meeting-Schedule)

- [x] **Documentation of how to contribute, with increasing detail as the project matures.**

 
Documentation on the workflow of how to contribute: [link to md#section](https://github.com/cubefs/cubefs/blob/master/CONTRIBUTING.md#workflow)

- [x] **Demonstrate contributor activity and recruitment.**

 
- Contributor activity can be measured and displayed using GitHub's built-in tools to assess the current participation of contributors
[The contributions of contributors](https://github.com/cubefs/cubefs/graphs/contributors)
[The level of community activity, including contributors' discussions, issues, pull requests, and other activities](https://github.com/cubefs/cubefs/graphs/community)

- Using strategies and methods such as participating in summits and events to attract new vendor and adoptors
	- 2024 KubeCon HONGKONG: CubeFS Boosts Efficiency of AI Production
	- 2023 KubeCon China:[Cloud Native Storage CubeFS, Empowering AI Acceleration](https://www.youtube.com/watch?v=JOio7Nps_II&t=1036s)
	- 2022 KubeCon NA:[The Best Practice of Machine Learning Platform Storage Based on CubeFS](https://www.youtube.com/watch?v=T8IjKLU9DWw&t=896s)
	- 2023 GOTC: [interview](https://baijiahao.baidu.com/s?id=1766755025138692049&wfr=spider&for=pc)
- By participating in developer events attract contributors
	- [Summer of Open Source](https://www.we2shopping.com/blog/2829327/)
	- [Developer activity 2024](#3105)
	- [Developer activity 2023](#1920)

- Ensure that new members can integrate smoothly and participate actively。For vendor enterprise users, there is a direct group chat for WeChat products. Generally, companies with technical capabilities will consider participating in development for feature customization

	- [OpenPie](https://github.com/cubefs/cubefs/pulls?q=is%3Apr+is%3Aclosed+author%3Amorphes1995)
	- [BIGO](https://github.com/cubefs/cubefs/pulls?q=is%3Apr+is%3Aclosed+author%3Aliubingxing)
	- [KE](https://github.com/cubefs/cubefs/pulls?q=is%3Apr+is%3Aclosed+author%3Ashyodx)

- attracted 2 committers to join through the Summer of Code event, and they continue to contribute to the community
	- [NaturalSelect](https://github.com/NaturalSelect) : [Contribution record](https://github.com/cubefs/cubefs/pulls?q=is%3Apr+is%3Aclosed+author%3ANaturalSelect)
	- [setcy](https://github.com/setcy) : [Contribution record](https://github.com/cubefs/cubefs/pulls?q=is%3Apr+setcy+is%3Aclosed)

## Engineering Principles

- [x] **Document project goals and objectives that illustrate the project’s differentiation in the Cloud Native landscape as well as outlines how this project fulfills an outstanding need and/or solves a problem differently.**

 
File storage and object storage are key in the storage domain. CubeFS is a file storage system that provides cloud-native file system capabilities and is compatible with object storage. Moreover, it offers a multitude of competitive features and capabilities.
The project’s differentiation is the main feature of CubeFS: [link to md#section](https://github.com/cubefs/cubefs/blob/master/README.md#what-can-you-build-with-cubefs)

- [x] **Document what the project does, and why it does it - including viable cloud native use cases.**

 

- [CubeFS Introduction](https://cubefs.io/docs/master/overview/introduction.html) includes what CubeFS does, and why it does it
- Use Case: How CubeFS Accelerates AI training in Hybrid Cloud platform: [link](https://cubefs.io/blog/useCases/oppo-ai.html)
- Documentation:[Integration with Kubernetes](https://cubefs.io/docs/master/ecology/k8s.html)

- [x] **Document and maintain a public roadmap or other forward looking planning document or tracking mechanism.**

 
CubeFS RoadMap: [link to md#section](https://github.com/cubefs/cubefs/blob/master/ROADMAP.md)

- [x] **Roadmap change process is documented.**

 
In general, a roadmap is created by collecting input from maintainers, committers, and community users. 
It involves selecting necessary items based on the dimensions of importance and urgency. 
Additionally, the roadmap takes into account the current available resources and long-term planning considerations for the project.
CubeFS RoadMap Updated need agreement from Steering commitee: [link to pr]](https://github.com/cubefs/cubefs/pull/3358)

- [x] **Document overview of project architecture and software design that demonstrates viable cloud native use cases, as part of the project's documentation.**

 
- CubeFS Introduction: [link](https://cubefs.io/docs/master/overview/introduction.html)
- Use Case: How CubeFS Accelerates AI training in Hybrid Cloud platform.[link](https://cubefs.io/blog/useCases/oppo-ai.html)
- Integration with Kubernetes: [link](https://cubefs.io/docs/master/ecology/k8s.html#csi-deployment-non-helm)
- K8s deployment: [link](https://cubefs.io/docs/master/deploy/k8s.html)

- [x] **Document the project's release process and guidelines publicly in a RELEASES.md or equivalent file that defines:** 
  - [x] Release expectations (scheduled or based on feature implementation)
  Releases: [link to md#section](https://github.com/cubefs/cubefs/blob/master/RELEASE.md#cubefs-releases)
  - [x] Tagging as stable, unstable, and security related releases
  Release schedule: [link to md#section](https://github.com/cubefs/cubefs/blob/master/RELEASE.md#release-schedule)
  - [x] Information on branch and tag strategies
  Types of branch: [link to md#section](https://github.com/cubefs/cubefs/blob/master/RELEASE.md#types-of-branch)
  - [x] Branch and platform support and length of support
  Versioning support by CubeFS: [link to md#section](https://github.com/cubefs/cubefs/blob/master/RELEASE.md#versioning-support-by-cubefs)
  - [x] Artifacts included in the release.
  Artifacts in the release: [link to md#section](https://github.com/cubefs/cubefs/blob/master/RELEASE.md#artifacts-included-in-the-release)
  - Additional information on topics such as LTS and edge releases are optional. Release expectations are a social contract between the project and its end users and hence changes to these should be well thought out, discussed, socialized and as necessary agreed upon by project leadership before getting rolled out.

 

- [x] **History of regular, quality releases.**

 

All components of CubeFS have been adopted by multiple vendors in the community and have undergone validation through online operations.
Official Releases: [link](https://github.com/cubefs/cubefs/releases)
## Security

Note: this section may be augemented by a joint-assessment performed by TAG Security.

### Suggested

- [x] **Achieving OpenSSF Best Practices silver or gold badge.**

 
CubeFS achieved OpenSSF Best Practices gold badge： [link](https://www.bestpractices.dev/zh-CN/projects/6232)

### Required

- [x] **Clearly defined and discoverable process to report security issues.**

 
CubeFS security documentation has the details. [link](https://github.com/cubefs/cubefs/blob/master/SECURITY.md#report-a-vulnerability)

- [x] **Enforcing Access Control Rules to secure the code base against attacks (Example: two factor authentication enforcement, and/or use of ACL tools.)**

 

1）Most maintainers have enabled two-factor authentication, and GitHub login requiring Authenticator two-step verification.
2）To strengthen code checks, we have integrated many tools in CI, includes ci-test-unit,ci-test-s3 and ci-sast [link](https://github.com/cubefs/cubefs/blob/master/.github/workflows/ci.yml) 
3）To further enhance security scanning, we perform routine static and dynamic scanning
- [gofumpt](https://github.com/cubefs/cubefs/blob/master/docker/script/run_format.sh)
- golint:In file docker-compose.yml:469 [link](https://github.com/cubefs/cubefs/blob/master/docker/docker-compose.yml)
- gosec:In file docker-compose.yuml:479 [link](https://github.com/cubefs/cubefs/blob/master/docker/docker-compose.yml)
- [fuzzers:Fuzz testing]https://github.com/cncf/cncf-fuzzing/pull/387

- [x] **Document assignment of security response roles and how reports are handled.**

 

CubeFS has established a Security Committee and clearly defined the roles and rules
Please reference: [link to md#section](https://github.com/cubefs/cubefs/blob/master/security/security-release-process.md)

- [x] **Document Security Self-Assessment.**

 

- And since the beginning of the project, we have always been concerned about security. Here is the Self-Assessment Documentation:[CubeFS-self-assessment.](https://github.com/cubefs/cubefs/blob/master/security/CubeFS-self-assessment.md)

- [x] **Third Party Security Review.**

  - [x] Moderate and low findings from the Third Party Security Review are planned/tracked for resolution as well as overall thematic findings, such as: improving project contribution guide providing a PR review guide to look for memory leaks and other vulnerabilities the project may be susceptible to by design or language choice ensuring adequate test coverage on all PRs.
  
 

CubeFS have passed the Third Party Security Review: [link](https://github.com/cubefs/cubefs/blob/master/security/CubeFS-security-audit-2023-report.pdf)
Some advisories already be fixed [link](https://github.com/cubefs/cubefs/security/advisories?state=Triage)

- [x] **Achieve the Open Source Security Foundation (OpenSSF) Best Practices passing badge.**

 
CubeFS achieved OpenSSF Best Practices gold badge: [link](https://www.bestpractices.dev/zh-CN/projects/6232)

### Suggested

N/A

### Required

- [x] **Publicly documented list of adopters, which may indicate their adoption level (dev/trialing, prod, etc.)**

 

The Documentation of adopters: [link](https://github.com/cubefs/cubefs/blob/master/ADOPTERS.md)

- [x] **Used in appropriate capacity by at least 3 independent + indirect/direct adopters, (these are not required to be in the publicly documented list of adopters)**

 
CubeFS has many adopters, and this list comprises vendors with closer ties to the community.
Adopters: [link to md#section](https://github.com/cubefs/cubefs/blob/master/ADOPTERS.md#success-stories)

The project provided the TOC with a list of adopters for verification of use of the project at the level expected, i.e. production use for graduation, dev/test for incubation.

- JD.com/e-commerce
- OPPO/electronic product supplier 
- NetEase/game publisher|portal website

- [] **TOC verification of adopters.**

 

Refer to the Adoption portion of this document.

- [x] **Clearly documented integrations and/or compatibility with other CNCF projects as well as non-CNCF projects.**

 

The Documentation of integrations: [link to md#section](https://github.com/cubefs/cubefs/depend/Readme.md)

**Comment by leonrayang** [comment]
record governance requirement
